name: PackageProject
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: 'true'
          submodules: 'recursive'
      - name: Zip Folder
        run: zip -r PCGTutorial.zip . -x ".git/*" ".github/*" ".git*"
      - name: Release to Github
        run: echo "Release"